### ISSUE TITLE
Requested Projects?

### ISSUE THREAD

**Issue by Shy** [SasaKaranovic/VU-Server#1]
Hey @SasaKaranovic. I got my dials this morning and I'm loving them. I'm mucking about with the API. Curious if you had any project examples or ideas you were looking for having created that I might be able to take a poke at while I play with these things.

**Comment by SasaKaranovic** [comment]
Hey @Shy ! That's awesome! I'm glad you are enjoying the dials (and thanks for preordering) :)

Thank you so much for the offer, we really appreciate it!
Right now we are focused on making the VU Server as robust and easy to use as possible.
Long term, making tens or hundreds of different VU1 application for PC usage, weather, stocks, fps counter and so on... does not seem like a very scalable approach. On top of that, we would have to convince people to use our app instead of their current favorite one.

So instead, our goal is to make VU dials as easy to integrate as possible with the long-term plan being that community and software developers start adopting/supporting VU dials in their applications either natively or through (community) plugins/addons.

With that said, if you have ideas for projects or want to take a poke at making a plugin/integrating VU1 dials into your favorite app/game we would be more than happy to see that.

**Comment by Shy** [comment]
That makes total sense. I've been focusing on more of the non gaming stuff (weather, trains, plaid integration) off a rasp pi that I run to manage my IoT stuff. Do you prefer messing with the demo app or do you have plans for a framework that would plugin into the existing server app? 

It would be cool if I could provide a simple python script that returns a json object which the server could then run on an interval. 

An emulator would be cool for the server if you got one in the works. I like to muck about when I'm away from home. Maybe I just need to pick up a single hub I can leave in my bag 😆.

**Comment by SasaKaranovic** [comment]
The VU Server is "just an API" or the abstraction layer between the applications running on the PC/Network and the actual VU hardware.

> It would be cool if I could provide a simple python script that returns a json object which the server could then run on an interval.

We do not plan to have plugins/addons/extensions for the VU server directly.

The idea is that VU Server provides a [web API](https://docs.vudials.com/api/dial_UID_set/) that can easily be consumed by any third party application/script/service.
It also provides (a very naive) access control in the form of API keys, so that you can [create an API key](https://docs.vudials.com/webui/manage_keys/) and assign it to application which then allows that application to only update the dials that are assigned to that API key.

One benefit of this is for example; if you already have an application that fetches/calculates some value that you want to show on the dials. You just simply make a [web API](https://docs.vudials.com/api/dial_UID_set/) request to update dial X with the value Y and that's it. And making a web request is very common thing to do and there are tons of tools and libraries that make this super easy to do.

> An emulator would be cool for the server if you got one in the works. I like to muck about when I'm away from home. Maybe I just need to pick up a single hub I can leave in my bag 😆.

The VU Server uses JSON for responses to all API requests so an emulator might be an overkill. When testing/debugging without the VU server/hub available, you could use cached/fake values in your application as the response from the server.

**Comment by Shy** [comment]
Ended up taking a first pass at some of this stuff. Work got away from me so took me a little bit to get started. https://github.com/Shy/vu-consumer if your curious.
