### ISSUE TITLE
Filter dial name to allow only [a-z0-9\-_ ] characters

### ISSUE THREAD

**Issue by SasaKaranovic** [SasaKaranovic/VU-Server#14]
### Proposal

VU Server should filter dial names to only allow:
- characters `a-z`
- numeric `0-9`
- space ` `
- underscore `_`
- hyphen-minus `-`

### Motivation

While it could be looked as unnecessary or even arbitrary limitation. 
The main motivation is to offer "soft protection" for third party applications that are interacting with the VU Server and in particular setting/retrieving dial names.

Containing special or non-ascii characters could potentially introduce unexpected results/behaviour in third party application which could end up hurting the VU Dials adoption rate.

Having a set of characters that do not require escaping or "special" processing is desired over current implementation.

### Implementation

Luckily implementation should be fairly simple because right now there is only one API endpoint that allows for dial (re)naming.

https://github.com/SasaKaranovic/VU-Server/blob/ee237b6d6842b43d927727743737e846b1415b53/server.py#L290

We should check/filter the dial name here and return appropriate response.

**Comment by feeph** [comment]
I can understand the reasoning, but this change would potentially prevent somebody from using native terms to describe their dials because äâèéöü and everything else are not acceptable. Arabic, Chinese, Greek, Japanese and Klingon are out as well. 

Since the primary point of assigning names to dials is to increase usability, limiting the names to `a-z0-9 _-` is probably too restrictive. I'd rather beef up the code to make sure it can handle random UTF-8 input.

_As far as I understood the code the device name is relevant only to the server software. The hub and the dials (the physical devices) have no idea what they are called._

**Comment by SasaKaranovic** [comment]
Handling these inputs on the server side is quite trivial.
Only purpose for dial name is to assign a "human readable" identifier to the unique ID that each dial has.

One potentially nice use of dial name is that in some other app, instead of using UID, you can say "Find the dial with the name `CPU Usage` and use it to display CPU usage". Ignoring for a second the obvious issue where many dials can have the same name.

However if third party applications/scripts now have to deal with non-ASCII input, the integration becomes needlessly more difficult.
I still think that more end-users would probably care if more third party apps can integrate with their dials rather than using a random non-ASCII characters.
