### ISSUE TITLE
Question: How often I can set the value

### ISSUE THREAD

**Issue by thamarnan** [SasaKaranovic/VU-Server#15]
Hello,

I'm exploring the frequency of setting the value through curl/wget
and wondering how often I can do the query for same dial or for different dial
Can I run a loop with very small sleep (eg 50ms)
Is there a recommended frequency to set the value

thanks!

**Comment by SasaKaranovic** [comment]
Hi @thamarnan

Good question. I would advise heavily against setting dials too often (ie like you mentioned, every 50ms) because it will increase the CPU load. And most likely dials won't have enough time to update if there is a large jump in the value.

I have tested the dials on my setup to update every `100ms` and it worked fine (with the significant increase in CPU usage).
That is why by default VU Server ships with software-limit of `200ms` by default.
The VU1 demo app by default updates dials every `500ms`.

It's hard to say what is the limit, because it depends on multiple factors that are external to VU dials. And as you start to push the interval, there will be bottlenecks or even worse things will start to fail/miss.

With that said... feel free to crank things to 11 and go crazy! :)
First, update your `config.yaml` file to reduce the `dial_update_period` -> https://github.com/SasaKaranovic/VU-Server/blob/master/config.yaml#L5
Then you can try in your app/script to update the dials more often.

Please, note once again that this is **not** a normal/intended mode of operation and you may experience some issues.
If this happens, I recommend reverting back to the default configuration.

**Comment by thamarnan** [comment]
Thanks for more details. I'll try it out.
