### ISSUE TITLE
Info for usability and working for linux pc

### ISSUE THREAD

**Issue by Docop2** [SasaKaranovic/VU-Server#3]
Hi
 I would like to know if you can put some minimal detail on how the dial are supposed to work, be used ? What are all those file. Do you have an appimage that we can simply run and config it ?  Or a .deb or something to install ? There is no way to do anything with those box currently.
Thanks in advance

**Comment by SasaKaranovic** [comment]
Hey @Docop2 !

Great question!
Right now we only have the installer for Windows. For Linux and Mac users can run the application from the source code.

To run the server app on Linux, you can install python and project dependencies and then run the `server.py` script.

To do that, you can type following commands in your terminal
```
sudo apt install git python3 python3-pip
git clone https://github.com/SasaKaranovic/VU-Server.git
cd VU-Server
pip3 install -r requirements.txt
```

You need to do the above steps just once.
After that you should be able to run the VU1 server with `python3 server.py`

In addition to the VU server, right now we have a [demo application](https://github.com/SasaKaranovic/VU-Demo-App) for Windows.

Our long-term goal is to have VU dials supported in all popular software packages either natively or through plugins/addons.
We are very aware that it will take some time (and a lot of love and support from the community) until we get there.
But we strongly believe that this is a better approach than designing many different competing software packages and forcing VU users to use them just so that they can use VU dials with them.

**Comment by Shy** [comment]
Something extra I would add to this, is I'd recommend using [pyenv](https://github.com/pyenv/pyenv) to keep things independent from your system. I ran things with python 3.9 and everything worked great. Not sure what specific python versions are supported.

**Comment by Shy** [comment]
Spun up a quick readme with info #4 .

**Comment by SasaKaranovic** [comment]
@Docop2 There is now a very [simple readme file](https://github.com/SasaKaranovic/VU-Server/blob/master/Running_from_source_on_linux.md) suggesting how to run VU Server from source code.

@Shy Thank you for suggesting using virtual environment. It's a good suggestion, although it might look "scary" to non-developers.
